/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.CardLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Jugador;
import modelo.Pregunta;
import servicios.GestorPreguntas;

/**
 *
 * @author Antonio
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private List<Pregunta> preguntas;
    private List<Pregunta> todasLasPreguntas;
    private int indicePreguntaActual = 0;
    private Timer temporizador;
    private int tiempoRestante;
    private Jugador jugadorActual;
    private String temaActual;
    private GestorPreguntas gestorPersistencia;

    public VentanaPrincipal(List<Pregunta> preguntas) {
        initComponents();
        this.todasLasPreguntas = preguntas;
        this.preguntas = new ArrayList<>(preguntas);

        setSize(800, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        gestorPersistencia = new GestorPreguntas();

        DefaultTableModel modelo = (DefaultTableModel) tblRanking.getModel();
        modelo.setRowCount(0);

        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        tblRanking.setRowSorter(sorter);
        sorter.setSortKeys(Arrays.asList(
                new RowSorter.SortKey(2, SortOrder.DESCENDING)
        ));

        rb1.addActionListener(e -> actualizarSeleccion());
        rb2.addActionListener(e -> actualizarSeleccion());
        rb3.addActionListener(e -> actualizarSeleccion());
        rb4.addActionListener(e -> actualizarSeleccion());

        if (preguntas != null && !preguntas.isEmpty()) {
            cambiarPantalla("inicio");
        } else {
            logger.warning("La lista de preguntas está vacía o es null.");
        }
    }

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setSize(800, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        contenedor = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        lblIntroduce = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnJugar = new javax.swing.JButton();
        panelTemas = new javax.swing.JPanel();
        btnCiencia = new javax.swing.JButton();
        btnLiteratura = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnGeografia = new javax.swing.JButton();
        lblGeografia = new javax.swing.JLabel();
        lblCiencia = new javax.swing.JLabel();
        lblLiteratura = new javax.swing.JLabel();
        lblHistoria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelPreguntaMultiple = new javax.swing.JPanel();
        lblPreguntaMultiple = new javax.swing.JLabel();
        rb3 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        btnRespuestaMultiple = new javax.swing.JButton();
        lblTiempoMultiple = new javax.swing.JLabel();
        panelPreguntaTexto = new javax.swing.JPanel();
        lblImagenTexto = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        btnRespuestaTexto = new javax.swing.JButton();
        lblPreguntaTexto = new javax.swing.JLabel();
        lblTiempoTexto = new javax.swing.JLabel();
        panelRanking = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRanking = new javax.swing.JTable();
        lblRanking = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedor.setLayout(new java.awt.CardLayout());

        panelInicio.setBackground(new java.awt.Color(240, 240, 240));

        lblIntroduce.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblIntroduce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIntroduce.setText("Introduce tu nombre");

        btnJugar.setText("Comenzar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblIntroduce, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(btnJugar)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lblIntroduce)
                .addGap(132, 132, 132)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(btnJugar)
                .addGap(120, 120, 120))
        );

        contenedor.add(panelInicio, "inicio");

        panelTemas.setBackground(new java.awt.Color(255, 255, 204));
        panelTemas.setPreferredSize(new java.awt.Dimension(800, 600));

        btnCiencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/ciencia96.png"))); // NOI18N
        btnCiencia.setBorderPainted(false);
        btnCiencia.setContentAreaFilled(false);
        btnCiencia.setFocusPainted(false);
        btnCiencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/ciencia128.png"))); // NOI18N
        btnCiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCienciaActionPerformed(evt);
            }
        });

        btnLiteratura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/literatura96.png"))); // NOI18N
        btnLiteratura.setBorderPainted(false);
        btnLiteratura.setContentAreaFilled(false);
        btnLiteratura.setFocusPainted(false);
        btnLiteratura.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/literatura128.png"))); // NOI18N
        btnLiteratura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiteraturaActionPerformed(evt);
            }
        });

        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/historia96.png"))); // NOI18N
        btnHistoria.setBorderPainted(false);
        btnHistoria.setContentAreaFilled(false);
        btnHistoria.setFocusPainted(false);
        btnHistoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/historia128.png"))); // NOI18N
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });

        btnGeografia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/geografia96.png"))); // NOI18N
        btnGeografia.setBorderPainted(false);
        btnGeografia.setContentAreaFilled(false);
        btnGeografia.setFocusPainted(false);
        btnGeografia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/geografia128.png"))); // NOI18N
        btnGeografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeografiaActionPerformed(evt);
            }
        });

        lblGeografia.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblGeografia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGeografia.setText("Geografía");
        lblGeografia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGeografiaMouseClicked(evt);
            }
        });

        lblCiencia.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCiencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCiencia.setText("Ciencia");
        lblCiencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCienciaMouseClicked(evt);
            }
        });

        lblLiteratura.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLiteratura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLiteratura.setText("Literatura");
        lblLiteratura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLiteraturaMouseClicked(evt);
            }
        });

        lblHistoria.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblHistoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHistoria.setText("Historia");
        lblHistoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHistoriaMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elige un tema");

        javax.swing.GroupLayout panelTemasLayout = new javax.swing.GroupLayout(panelTemas);
        panelTemas.setLayout(panelTemasLayout);
        panelTemasLayout.setHorizontalGroup(
            panelTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTemasLayout.createSequentialGroup()
                .addGroup(panelTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTemasLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(panelTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelTemasLayout.createSequentialGroup()
                                .addGroup(panelTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTemasLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(btnCiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTemasLayout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addComponent(btnHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTemasLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelTemasLayout.createSequentialGroup()
                                .addComponent(lblGeografia, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(lblLiteratura, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelTemasLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnGeografia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(btnLiteratura, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTemasLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        panelTemasLayout.setVerticalGroup(
            panelTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTemasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGeografia, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnLiteratura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeografia)
                    .addComponent(lblLiteratura, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(panelTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCiencia, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnHistoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panelTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiencia)
                    .addComponent(lblHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        contenedor.add(panelTemas, "temas");

        panelPreguntaMultiple.setBackground(new java.awt.Color(200, 255, 200));

        lblPreguntaMultiple.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPreguntaMultiple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreguntaMultiple.setText("Pregunta Multiple");

        buttonGroup1.add(rb3);

        buttonGroup1.add(rb2);

        buttonGroup1.add(rb4);

        buttonGroup1.add(rb1);
        rb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb1MouseClicked(evt);
            }
        });

        btnRespuestaMultiple.setText("Responder");
        btnRespuestaMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaMultipleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPreguntaMultipleLayout = new javax.swing.GroupLayout(panelPreguntaMultiple);
        panelPreguntaMultiple.setLayout(panelPreguntaMultipleLayout);
        panelPreguntaMultipleLayout.setHorizontalGroup(
            panelPreguntaMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaMultipleLayout.createSequentialGroup()
                .addGroup(panelPreguntaMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPreguntaMultipleLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblPreguntaMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPreguntaMultipleLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(panelPreguntaMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPreguntaMultipleLayout.createSequentialGroup()
                                .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPreguntaMultipleLayout.createSequentialGroup()
                                .addComponent(rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(150, 150, 150)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(panelPreguntaMultipleLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(btnRespuestaMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTiempoMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        panelPreguntaMultipleLayout.setVerticalGroup(
            panelPreguntaMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaMultipleLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPreguntaMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPreguntaMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(panelPreguntaMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPreguntaMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRespuestaMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempoMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        contenedor.add(panelPreguntaMultiple, "pregunta");

        panelPreguntaTexto.setBackground(new java.awt.Color(200, 230, 255));
        panelPreguntaTexto.setPreferredSize(new java.awt.Dimension(800, 600));

        btnRespuestaTexto.setText("Responder");
        btnRespuestaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaTextoActionPerformed(evt);
            }
        });

        lblPreguntaTexto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPreguntaTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreguntaTexto.setText("Pregunta Texto");

        javax.swing.GroupLayout panelPreguntaTextoLayout = new javax.swing.GroupLayout(panelPreguntaTexto);
        panelPreguntaTexto.setLayout(panelPreguntaTextoLayout);
        panelPreguntaTextoLayout.setHorizontalGroup(
            panelPreguntaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaTextoLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addGroup(panelPreguntaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImagenTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPreguntaTextoLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(panelPreguntaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPreguntaTextoLayout.createSequentialGroup()
                        .addComponent(lblPreguntaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPreguntaTextoLayout.createSequentialGroup()
                        .addComponent(btnRespuestaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227)
                        .addComponent(lblTiempoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        panelPreguntaTextoLayout.setVerticalGroup(
            panelPreguntaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntaTextoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPreguntaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblImagenTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(panelPreguntaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRespuestaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        contenedor.add(panelPreguntaTexto, "texto");

        panelRanking.setBackground(new java.awt.Color(255, 255, 255));

        tblRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jugador", "Tema", "Puntuación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRanking);

        lblRanking.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRanking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRanking.setText("Ranking");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRankingLayout = new javax.swing.GroupLayout(panelRanking);
        panelRanking.setLayout(panelRankingLayout);
        panelRankingLayout.setHorizontalGroup(
            panelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRankingLayout.createSequentialGroup()
                .addGroup(panelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRankingLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRankingLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(panelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRankingLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        panelRankingLayout.setVerticalGroup(
            panelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRankingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblRanking)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(panelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(79, 79, 79))
        );

        contenedor.add(panelRanking, "ranking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRespuestaMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaMultipleActionPerformed
        Pregunta p = preguntas.get(indicePreguntaActual);

        String seleccion = null;

        if (rb1.isSelected()) {
            seleccion = p.getOpciones()[0];
        }
        if (rb2.isSelected()) {
            seleccion = p.getOpciones()[1];
        }
        if (rb3.isSelected()) {
            seleccion = p.getOpciones()[2];
        }
        if (rb4.isSelected()) {
            seleccion = p.getOpciones()[3];
        }

        if (seleccion == null) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una opción antes de continuar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (seleccion.equals(p.getRespuestaCorrecta())) {
            jugadorActual.sumarPunto();
            JOptionPane.showMessageDialog(this, "¡Correcto!", "Respuesta", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Incorrecto. Inténtalo de nuevo.", "Respuesta", JOptionPane.ERROR_MESSAGE);
        }

        indicePreguntaActual++;

        if (indicePreguntaActual < preguntas.size()) {
            mostrarPregunta();
        } else {
            if (temporizador != null && temporizador.isRunning()) {
                temporizador.stop();
            }
            gestorPersistencia.agregarJugador(jugadorActual);
            añadirResultadoRanking();
            txtNombre.setText("");
            txtRespuesta.setText("");
            cambiarPantalla("ranking");
        }
    }//GEN-LAST:event_btnRespuestaMultipleActionPerformed

    private void rb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1MouseClicked

    private void btnRespuestaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaTextoActionPerformed
        Pregunta p = preguntas.get(indicePreguntaActual);

        String respuestaJugador = txtRespuesta.getText();

        if (respuestaJugador.equalsIgnoreCase(p.getRespuestaCorrecta())) {
            jugadorActual.sumarPunto();
            JOptionPane.showMessageDialog(this, "¡Correcto!", "Respuesta", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Incorrecto. Inténtalo de nuevo.", "Respuesta", JOptionPane.ERROR_MESSAGE);
        }

        indicePreguntaActual++;

        if (indicePreguntaActual < preguntas.size()) {
            mostrarPregunta();
        } else {
            if (temporizador != null && temporizador.isRunning()) {
                temporizador.stop();
            }
            gestorPersistencia.agregarJugador(jugadorActual);
            añadirResultadoRanking();
            txtNombre.setText("");
            txtRespuesta.setText("");
            cambiarPantalla("ranking");
        }
    }//GEN-LAST:event_btnRespuestaTextoActionPerformed

    private void btnCienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCienciaActionPerformed
        jugadorActual.setTema("Ciencia");
        iniciarJuegoPorTema("Ciencia");
    }//GEN-LAST:event_btnCienciaActionPerformed

    private void lblGeografiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGeografiaMouseClicked
        btnGeografia.doClick();
    }//GEN-LAST:event_lblGeografiaMouseClicked

    private void lblLiteraturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLiteraturaMouseClicked
        btnLiteratura.doClick();
    }//GEN-LAST:event_lblLiteraturaMouseClicked

    private void lblCienciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCienciaMouseClicked
        btnCiencia.doClick();
    }//GEN-LAST:event_lblCienciaMouseClicked

    private void lblHistoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoriaMouseClicked
        btnHistoria.doClick();
    }//GEN-LAST:event_lblHistoriaMouseClicked

    private void btnGeografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeografiaActionPerformed
        jugadorActual.setTema("Geografia");
        iniciarJuegoPorTema("Geografia");
    }//GEN-LAST:event_btnGeografiaActionPerformed

    private void btnLiteraturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiteraturaActionPerformed
        jugadorActual.setTema("Literatura");
        iniciarJuegoPorTema("Literatura");
    }//GEN-LAST:event_btnLiteraturaActionPerformed

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
        jugadorActual.setTema("Historia");
        iniciarJuegoPorTema("Historia");
    }//GEN-LAST:event_btnHistoriaActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed

        String nombre = txtNombre.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce un nombre.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (nombre.length() > 50) {
            txtNombre.setText("");
            JOptionPane.showMessageDialog(this, "El nombre no puede tener más de 50 caracteres.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        jugadorActual = new Jugador(nombre);

        cambiarPantalla("temas");


    }//GEN-LAST:event_btnJugarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.preguntas = new ArrayList<>(todasLasPreguntas);
        this.indicePreguntaActual = 0;

        if (temporizador != null && temporizador.isRunning()) {
            temporizador.stop();
        }
        cambiarPantalla("inicio");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    public void cambiarPantalla(String nombre) {
        CardLayout card = (CardLayout) contenedor.getLayout();
        card.show(contenedor, nombre);
    }

    public void mostrarPregunta() {

        buttonGroup1.clearSelection();
        rb1.setBorder(null);
        rb2.setBorder(null);
        rb3.setBorder(null);
        rb4.setBorder(null);

        if (indicePreguntaActual >= preguntas.size()) {
            System.out.println("Se acabaron las preguntas");
            return;
        }

        Pregunta p = preguntas.get(indicePreguntaActual);

        if (p.getTipo() == Pregunta.Tipo.MULTIPLE) {

            cambiarPantalla("pregunta");

            lblPreguntaMultiple.setText(p.getEnunciado());

            configurarRadio(rb1, p.getOpciones()[0]);
            configurarRadio(rb2, p.getOpciones()[1]);
            configurarRadio(rb3, p.getOpciones()[2]);
            configurarRadio(rb4, p.getOpciones()[3]);

        } else if (p.getTipo() == Pregunta.Tipo.TEXTO) {

            cambiarPantalla("texto");

            lblPreguntaTexto.setText(p.getEnunciado());

            configurarImagenLabel(lblImagenTexto, p.getImagen(), 200, 240);
            txtRespuesta.setText("");
        }
        iniciarTemporizador();
        revalidate();
        repaint();
    }

    private void configurarRadio(JRadioButton rb, String ruta) {

        ImageIcon icon = new ImageIcon(ruta);

        Image img = icon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);

        rb.setIcon(new ImageIcon(img));

        rb.setBorderPainted(true);
        rb.setFocusPainted(false);
        rb.setContentAreaFilled(false);
        rb.setHorizontalAlignment(SwingConstants.CENTER);

    }

    private void actualizarSeleccion() {

        rb1.setBorder(null);
        rb2.setBorder(null);
        rb3.setBorder(null);
        rb4.setBorder(null);

        if (rb1.isSelected()) {
            rb1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLUE, 4));
        }

        if (rb2.isSelected()) {
            rb2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLUE, 4));
        }

        if (rb3.isSelected()) {
            rb3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLUE, 4));
        }

        if (rb4.isSelected()) {
            rb4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLUE, 4));
        }

    }

    private void configurarImagenLabel(javax.swing.JLabel label, String ruta, int ancho, int alto) {
        if (ruta == null || ruta.isEmpty()) {
            label.setIcon(null);
            return;
        }

        ImageIcon icon = new ImageIcon(ruta);
        Image img = icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));
    }

    private void iniciarTemporizador() {

        if (!panelPreguntaMultiple.isVisible() && !panelPreguntaTexto.isVisible()) {
            return;
        }

        tiempoRestante = 30;

        if (temporizador != null && temporizador.isRunning()) {
            temporizador.stop();
        }

        temporizador = new Timer(1000, e -> {
            tiempoRestante--;

            if (panelPreguntaMultiple.isVisible()) {
                lblTiempoMultiple.setText("Tiempo: " + tiempoRestante + "s");
            } else if (panelPreguntaTexto.isVisible()) {
                lblTiempoTexto.setText("Tiempo: " + tiempoRestante + "s");
            }

            if (tiempoRestante <= 0) {
                temporizador.stop();
                JOptionPane.showMessageDialog(this, "¡Tiempo agotado!", "Tiempo", JOptionPane.WARNING_MESSAGE);

                indicePreguntaActual++;
                if (indicePreguntaActual < preguntas.size()) {
                    mostrarPregunta();
                } else {
                    if (temporizador != null && temporizador.isRunning()) {
                        temporizador.stop();
                    }
                    gestorPersistencia.agregarJugador(jugadorActual);
                    añadirResultadoRanking();
                    txtNombre.setText("");
                    txtRespuesta.setText("");
                    cambiarPantalla("ranking");
                }
            }
        });

        temporizador.start();
    }

    public void iniciarJuegoPorTema(String tema) {
        temaActual = tema;
        List<Pregunta> preguntasFiltradas = new ArrayList<>();
        for (Pregunta p : todasLasPreguntas) {
            if (p.getTema().equalsIgnoreCase(tema)) {
                preguntasFiltradas.add(p);
            }
        }

        if (preguntasFiltradas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay preguntas disponibles para este tema.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        this.preguntas = preguntasFiltradas;
        this.indicePreguntaActual = 0;

        mostrarPregunta();
    }

    public void añadirResultadoRanking() {

        DefaultTableModel modelo = (DefaultTableModel) tblRanking.getModel();
        modelo.setRowCount(0);

        List<Jugador> ranking = gestorPersistencia.getRanking();

        for (Jugador j : ranking) {
            modelo.addRow(new Object[]{
                j.getNombre(),
                j.getTema(),
                j.getPuntuacion()
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCiencia;
    private javax.swing.JButton btnGeografia;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnLiteratura;
    private javax.swing.JButton btnRespuestaMultiple;
    private javax.swing.JButton btnRespuestaTexto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCiencia;
    private javax.swing.JLabel lblGeografia;
    private javax.swing.JLabel lblHistoria;
    private javax.swing.JLabel lblImagenTexto;
    private javax.swing.JLabel lblIntroduce;
    private javax.swing.JLabel lblLiteratura;
    private javax.swing.JLabel lblPreguntaMultiple;
    private javax.swing.JLabel lblPreguntaTexto;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JLabel lblTiempoMultiple;
    private javax.swing.JLabel lblTiempoTexto;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelPreguntaMultiple;
    private javax.swing.JPanel panelPreguntaTexto;
    private javax.swing.JPanel panelRanking;
    private javax.swing.JPanel panelTemas;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JTable tblRanking;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
